Updated JooYoung's info
rstudio/rticles pull request #438
Opened 2021-09-07 18:59 UTC by jooyoungseo

Thanks for your final touch, @cderv! This PR updates my information (e.g., email; affiliation) following #251.

2021-09-07 18:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/rticles?pullRequest=438) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/rticles?pullRequest=438) before we can accept your contribution.<br/><hr/>**JooYoung Seo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/rticles?pullRequest=438) it.</sub>

2021-09-07 19:35 UTC, cderv requested changes
Thanks! 

I agree that DESCRIPTION should be updated. However, maybe we should not put your information into the skeleton Rmd so that your information are not left in all template document created and we do not have to update them while they change. 

Don't you think ?

2021-09-08 13:05 UTC, jooyoungseo commented
Agreed, @cderv! I will update the default skeleton author info following the original template by tomorrow.

2021-09-09 17:43 UTC, cderv approved these changes
Thanks !

2021-09-09 17:43 UTC, merged