Enable more authors in RSS template
rstudio/rticles pull request #466
Opened 2022-02-08 19:22 UTC by dmi3kno

This is a breaking change with regards to `article_rss()`. I needed more authors and optional email field, so I decided to refactor this template a bit. The class used by RSS has some known issues with formatting table captions. 
https://tex.stackexchange.com/questions/322231/caption-makes-table-move-in-statsoc-class
The trick is to remove .aux file before re-rendering. I wonder if we should write this somewhere in the documentation.

2022-02-09 14:04 UTC, cderv requested changes
Thanks! 

Regarding the breaking change, as the fields don't have the same names, we could probably support both in the template (like `$if(author)$` would be the old way and `$if(authors)$` the new way) 

Regarding the table bug, we can also not support Pandoc's table (at least the one that does not work) inside this format. I am not quite sure to have fully comprehend the issue, do you have a reproducible example ? 
If we need to do something special (like a patch or something) we can do that in the format function (as post processor or something else). Removing aux file and re-rendering is maybe possible but it seems a pretty hard hack. 

I just need to understand what is the issue really. It seems that `statsoc.cls` has not been updated since a long time.  

Small change needed also as we need to live preferably without a minimum pandoc version. 

Thanks

2022-02-15 19:09 UTC, dmi3kno commented on inst/rmarkdown/templates/rss/resources/template.tex
> +\author[$short_author$]{$it.name$}
Yes, but that's how it was envisaged all along look at lines 21-33 in the code today. Besides it is not the same value. It's only the same index. The author name which will be displayed is specified in curly brackets.

2022-02-15 19:10 UTC, dmi3kno commented on inst/rmarkdown/templates/rss/resources/template.tex
> +$if(it.email)$\email{$it.email$}$endif$
Agreed.

2022-02-16 11:25 UTC, cderv approved these changes
Thanks! 

I'll tweak a little and merge

2022-02-16 11:55 UTC, merged